/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppTimeRouteImport } from './routes/app.time'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppLiveSessionsRouteImport } from './routes/app.live-sessions'
import { Route as AppFinancialsRouteImport } from './routes/app.financials'
import { Route as AppEducationRouteImport } from './routes/app.education'
import { Route as AppDraftingRouteImport } from './routes/app.drafting'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDeadlinesRouteImport } from './routes/app.deadlines'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCourtroomRouteImport } from './routes/app.courtroom'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppMeetingsIndexRouteImport } from './routes/app.meetings.index'
import { Route as AppCasesIndexRouteImport } from './routes/app.cases.index'
import { Route as AppMeetingsIdRouteImport } from './routes/app.meetings.$id'
import { Route as AppCasesCaseIdRouteImport } from './routes/app.cases.$caseId'
import { Route as ApiElevenlabsScribeTokenRouteImport } from './routes/api.elevenlabs.scribe-token'
import { Route as AppMeetingsJoinRoomRouteImport } from './routes/app.meetings.join.$room'

const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveSessionsRoute = AppLiveSessionsRouteImport.update({
  id: '/live-sessions',
  path: '/live-sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancialsRoute = AppFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppRoute,
} as any)
const AppEducationRoute = AppEducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftingRoute = AppDraftingRouteImport.update({
  id: '/drafting',
  path: '/drafting',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDeadlinesRoute = AppDeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCourtroomRoute = AppCourtroomRouteImport.update({
  id: '/courtroom',
  path: '/courtroom',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIndexRoute = AppMeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsIdRoute = AppMeetingsIdRouteImport.update({
  id: '/meetings/$id',
  path: '/meetings/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const ApiElevenlabsScribeTokenRoute =
  ApiElevenlabsScribeTokenRouteImport.update({
    id: '/api/elevenlabs/scribe-token',
    path: '/api/elevenlabs/scribe-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppMeetingsJoinRoomRoute = AppMeetingsJoinRoomRouteImport.update({
  id: '/meetings/join/$room',
  path: '/meetings/join/$room',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/courtroom': typeof AppCourtroomRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deadlines': typeof AppDeadlinesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drafting': typeof AppDraftingRoute
  '/app/education': typeof AppEducationRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/live-sessions': typeof AppLiveSessionsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/time': typeof AppTimeRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/app/meetings/$id': typeof AppMeetingsIdRoute
  '/app/cases/': typeof AppCasesIndexRoute
  '/app/meetings/': typeof AppMeetingsIndexRoute
  '/app/meetings/join/$room': typeof AppMeetingsJoinRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/courtroom': typeof AppCourtroomRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deadlines': typeof AppDeadlinesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drafting': typeof AppDraftingRoute
  '/app/education': typeof AppEducationRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/live-sessions': typeof AppLiveSessionsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/time': typeof AppTimeRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/app/meetings/$id': typeof AppMeetingsIdRoute
  '/app/cases': typeof AppCasesIndexRoute
  '/app/meetings': typeof AppMeetingsIndexRoute
  '/app/meetings/join/$room': typeof AppMeetingsJoinRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/set-password': typeof SetPasswordRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRoute
  '/app/courtroom': typeof AppCourtroomRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/deadlines': typeof AppDeadlinesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/drafting': typeof AppDraftingRoute
  '/app/education': typeof AppEducationRoute
  '/app/financials': typeof AppFinancialsRoute
  '/app/live-sessions': typeof AppLiveSessionsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/research': typeof AppResearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/time': typeof AppTimeRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/elevenlabs/scribe-token': typeof ApiElevenlabsScribeTokenRoute
  '/app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/app/meetings/$id': typeof AppMeetingsIdRoute
  '/app/cases/': typeof AppCasesIndexRoute
  '/app/meetings/': typeof AppMeetingsIndexRoute
  '/app/meetings/join/$room': typeof AppMeetingsJoinRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/set-password'
    | '/app/activity'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/clients'
    | '/app/courtroom'
    | '/app/dashboard'
    | '/app/deadlines'
    | '/app/documents'
    | '/app/drafting'
    | '/app/education'
    | '/app/financials'
    | '/app/live-sessions'
    | '/app/onboarding'
    | '/app/research'
    | '/app/settings'
    | '/app/team'
    | '/app/time'
    | '/share/$token'
    | '/app/'
    | '/api/elevenlabs/scribe-token'
    | '/app/cases/$caseId'
    | '/app/meetings/$id'
    | '/app/cases/'
    | '/app/meetings/'
    | '/app/meetings/join/$room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/set-password'
    | '/app/activity'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/clients'
    | '/app/courtroom'
    | '/app/dashboard'
    | '/app/deadlines'
    | '/app/documents'
    | '/app/drafting'
    | '/app/education'
    | '/app/financials'
    | '/app/live-sessions'
    | '/app/onboarding'
    | '/app/research'
    | '/app/settings'
    | '/app/team'
    | '/app/time'
    | '/share/$token'
    | '/app'
    | '/api/elevenlabs/scribe-token'
    | '/app/cases/$caseId'
    | '/app/meetings/$id'
    | '/app/cases'
    | '/app/meetings'
    | '/app/meetings/join/$room'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/set-password'
    | '/app/activity'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/clients'
    | '/app/courtroom'
    | '/app/dashboard'
    | '/app/deadlines'
    | '/app/documents'
    | '/app/drafting'
    | '/app/education'
    | '/app/financials'
    | '/app/live-sessions'
    | '/app/onboarding'
    | '/app/research'
    | '/app/settings'
    | '/app/team'
    | '/app/time'
    | '/share/$token'
    | '/app/'
    | '/api/elevenlabs/scribe-token'
    | '/app/cases/$caseId'
    | '/app/meetings/$id'
    | '/app/cases/'
    | '/app/meetings/'
    | '/app/meetings/join/$room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SetPasswordRoute: typeof SetPasswordRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiElevenlabsScribeTokenRoute: typeof ApiElevenlabsScribeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/time': {
      id: '/app/time'
      path: '/time'
      fullPath: '/app/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live-sessions': {
      id: '/app/live-sessions'
      path: '/live-sessions'
      fullPath: '/app/live-sessions'
      preLoaderRoute: typeof AppLiveSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financials': {
      id: '/app/financials'
      path: '/financials'
      fullPath: '/app/financials'
      preLoaderRoute: typeof AppFinancialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/education': {
      id: '/app/education'
      path: '/education'
      fullPath: '/app/education'
      preLoaderRoute: typeof AppEducationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drafting': {
      id: '/app/drafting'
      path: '/drafting'
      fullPath: '/app/drafting'
      preLoaderRoute: typeof AppDraftingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deadlines': {
      id: '/app/deadlines'
      path: '/deadlines'
      fullPath: '/app/deadlines'
      preLoaderRoute: typeof AppDeadlinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courtroom': {
      id: '/app/courtroom'
      path: '/courtroom'
      fullPath: '/app/courtroom'
      preLoaderRoute: typeof AppCourtroomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings/': {
      id: '/app/meetings/'
      path: '/meetings'
      fullPath: '/app/meetings/'
      preLoaderRoute: typeof AppMeetingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases/': {
      id: '/app/cases/'
      path: '/cases'
      fullPath: '/app/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings/$id': {
      id: '/app/meetings/$id'
      path: '/meetings/$id'
      fullPath: '/app/meetings/$id'
      preLoaderRoute: typeof AppMeetingsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cases/$caseId': {
      id: '/app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/app/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/elevenlabs/scribe-token': {
      id: '/api/elevenlabs/scribe-token'
      path: '/api/elevenlabs/scribe-token'
      fullPath: '/api/elevenlabs/scribe-token'
      preLoaderRoute: typeof ApiElevenlabsScribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/meetings/join/$room': {
      id: '/app/meetings/join/$room'
      path: '/meetings/join/$room'
      fullPath: '/app/meetings/join/$room'
      preLoaderRoute: typeof AppMeetingsJoinRoomRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCourtroomRoute: typeof AppCourtroomRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeadlinesRoute: typeof AppDeadlinesRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppDraftingRoute: typeof AppDraftingRoute
  AppEducationRoute: typeof AppEducationRoute
  AppFinancialsRoute: typeof AppFinancialsRoute
  AppLiveSessionsRoute: typeof AppLiveSessionsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTimeRoute: typeof AppTimeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppMeetingsIdRoute: typeof AppMeetingsIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppMeetingsIndexRoute: typeof AppMeetingsIndexRoute
  AppMeetingsJoinRoomRoute: typeof AppMeetingsJoinRoomRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRoute,
  AppCourtroomRoute: AppCourtroomRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeadlinesRoute: AppDeadlinesRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppDraftingRoute: AppDraftingRoute,
  AppEducationRoute: AppEducationRoute,
  AppFinancialsRoute: AppFinancialsRoute,
  AppLiveSessionsRoute: AppLiveSessionsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppResearchRoute: AppResearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTimeRoute: AppTimeRoute,
  AppIndexRoute: AppIndexRoute,
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppMeetingsIdRoute: AppMeetingsIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppMeetingsIndexRoute: AppMeetingsIndexRoute,
  AppMeetingsJoinRoomRoute: AppMeetingsJoinRoomRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SetPasswordRoute: SetPasswordRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiElevenlabsScribeTokenRoute: ApiElevenlabsScribeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
